Features/bgm 623 helper functions stake bpt
xave-finance/halodao-interface-archive pull request #2
Opened 2021-03-17 17:11 UTC by ernestpascual

## Description of Changes

Working staking and unstaking of whitelisted pool tokens. Contracts used here (03-16-21 version): https://halodao-project.slack.com/archives/C014UQMQA9X/p1615904657025400

Please check the slack message for the missing functions in the smart contract. https://halodao-project.slack.com/archives/C014UQMQA9X/p1615999184029400

## How to test

**Pre-conditions**
1. Make sure that you have some BPT from this pool `0x37f80ac90235ce0d3911952d0ce49071a0ffdb1e`. If you don't have any tokens, you can get some on this pool: https://kovan.pools.balancer.exchange/#/pool/0x37f80ac90235ce0d3911952d0ce49071a0ffdb1e/
2. Check if the BPT balances are loading. If you're running this for the first time, you would see your current BPT balance and 0 BPT from the contract

**Staking**
1. Enter the desired number of tokens to be staked. If you have enough balance, the button will be enabled. Else, it will be disabled
2. If the button is enabled, click stake. 
3. Metamask will popup to send the transaction for approving the token transfer
4. Once the transaction is confirmed, metamask will popup again to call the `depositAmmLpTokens()` in the smart contract. Note that if this transaction fails, you can add some more in the gas limit
5. After the transaction is confirmed, the input field will reset to zero and you will see your balances change.

**Unstaking**
1. Enter the desired number of tokens to be unstaked. If you have enough balance, the button will be enabled. Else, it will be disabled
2. If the button is enabled, click unstake. 
3. Metamask will popup again to call the `withdrawAmmLpTokens()` in the smart contract. Note that if this transaction fails, you can add some more in the gas limit
4. After the transaction is confirmed, the input field will reset to zero and you will see your balances change.

[Link to Jira Ticket](https://lifemesh.atlassian.net/browse/BGM-623)
[Link to Jira Ticket](https://lifemesh.atlassian.net/browse/BGM-626)
[Link to Jira Ticket](https://lifemesh.atlassian.net/browse/BGM-629)

### Developer Checklist:

- [x] This PR has a corresponding JIRA ticket
- [x] My branch conforms with our naming convention i.e. `feature/BGM-XXX-description`
- [ ] ~~I have written new tests for your core changes, as applicable~~
- [x] ~~I have successfully ran tests locally~~ Did manual checking in the UI

### Reviewers Checklist:

- [ ] Code is readable and understandable; any unclear parts have explanations
- [ ] Code style confirms to typescript rules
- [ ] UI/UX changes match the corresponding figma/other design resources, if applicable
- [ ] I have successfully ran tests locally

2021-03-18 13:53 UTC, schystz commented on src/constants/index.ts
> +      tokenAddress: wethDaiAddressTokenKovan
@ernestpascual the value of this token address seems to be the same as the balancer pool contract address:

```
REACT_APP_POOL_WETHDAI_ADDRESS_KOVAN=0x37f80ac90235ce0d3911952d0ce49071a0ffdb1e
REACT_APP_LP_TOKEN_ADDRESS=0x37f80ac90235ce0d3911952d0ce49071a0ffdb1e
```

If its the case, we don't need this extra prop & env var, and can simply reuse `REACT_APP_POOL_WETHDAI_ADDRESS_KOVAN `

2021-03-18 13:55 UTC, schystz commented on src/hooks/useContract.ts
> +      console.log('Here: ', address)
@ernestpascual can we remove this debug log?

2021-03-18 13:57 UTC, schystz commented on src/hooks/useContract.ts
> +      console.log('Here: ', address)
Actually saw some more debug logs on `BalancerPoolCard.tsx`, not sure if those are useful or better to remove them if they are no longer necessary

2021-03-18 13:58 UTC, schystz commented on src/components/PositionCard/BalancerPoolCard.tsx
> +                disabled={!(parseInt(stakeAmount) > 0 && parseInt(stakeAmount) <= bptBalance) || loading}
@ernestpascual I think we can use `parseFloat` here instead of `parseInt` so user can enter decimal values less than 1, e.g. 0.5 BPT. Same with line 193 below.

2021-03-18 14:03 UTC, schystz reviewed
@ernestpascual tested this locally and the stake/unstake function worked fine for me, at least in terms of the BPT deducted and added back to my wallet. I have yet to verify the Rewards part (maybe tom I'll have some).

I left some minor code comments, but 1 thing which seems erroneous is the allowance. Every time I stake (even if the BTP is lower than previous), metamask always shows the "allow to spend" confirmation before the actual "stake" transaction. When I added a console log, the allowance returned by the contract is always 0.

One improvement we can also add is to show loading indicators in the buttons while the transactions are happening in the background. And some toasts to indicate successful/fail operations. This can be a separate task though cc: @tracyarciaga

2021-03-18 18:29 UTC, ernestpascual commented on src/constants/index.ts
> +      tokenAddress: wethDaiAddressTokenKovan
i was thinking they were different contracts. ill just remove the other one. thanks for spotting!

2021-03-18 18:29 UTC, ernestpascual commented on src/hooks/useContract.ts
> +      console.log('Here: ', address)
I can remove this log. The one's we can still probably need since it's sending back the transaction receipt

2021-03-18 18:29 UTC, ernestpascual commented on src/components/PositionCard/BalancerPoolCard.tsx
> +                disabled={!(parseInt(stakeAmount) > 0 && parseInt(stakeAmount) <= bptBalance) || loading}
will do!

2021-03-18 20:08 UTC, ernestpascual commented
**Updated:**
Env side (uploaded the new env file in 1pass):
Removed the other address in env 
Add the new rewards address in env

dApp:
- Remove unused debug log
- Renamed functions from the latest PR from tracy and updated ABIs
- Change parseInt to parseFloat

In Progress:
Allowance issue: i still get 0 from time to time. sometimes it has a value, sometimes it becomes less of the approved allowance then it resets back to zero. still investigating this bit

2021-03-19 04:04 UTC, schystz commented on src/hooks/useContract.ts
> +      console.log('Here: ', address)
Ok sounds good!

2021-03-19 04:07 UTC, schystz commented
Looking good so far.

2 issues we are looking at right now:
- HALO rewards still showing 0
- "allow to spend" metamask pop-up always showing

2021-03-22 15:55 UTC, ernestpascual commented
Updates: 
- UX improvements : spinners upon waiting for transaction, confetti after successful staking and claiming rewards
- Claim Rewards, Unstake and Unclaim Rewards function (https://drive.google.com/file/d/1IjiZZGXo38wHFecDHab16FpEYxNyHUuY/view video reference for now, you can check on your end)


Note: Allowance still causing some issues, but seem to be from the BPT contract. We can add a separate task for this if ever to close this PR.  Let me know what you think @ctverceles  @schystz  @tracyarciaga

2021-03-23 09:51 UTC, schystz commented on src/components/PositionCard/BalancerPoolCard.tsx
> +  }, [bptBalance, getAllowance, getUnclaimedPoolReward, getUserTotalTokenslByPoolAddress, getBptBalance])
@ernestpascual getting a compile warning here:

```
./src/components/PositionCard/BalancerPoolCard.tsx
  Line 95:6:  React Hook useEffect has a missing dependency: 'loading'. Either include it or remove the dependency array. You can also do a functional update 'setLoading(l => ...)' if you only need 'loading' in the 'setLoading' call  react-hooks/exhaustive-deps
```

2021-03-23 09:54 UTC, schystz commented on src/components/PositionCard/BalancerPoolCard.tsx
> +        const approvalTxn = await lpTokenContract!.approve(HALO_REWARDS_ADDRESS, lpTokenAmount.toString())
@ernestpascual after looking at the forked code, sushiswap seem to use the max amount here instead of the actual amount to be transferred. Not sure if it will solve the issue but something we can try. I was previously concerned on the metamask pop-up but it looks like the amount to be approved is not shown to the user at all so I think its fine to use max amount.

Here's a sample snippet from `useSaave` hook:

```
const tx = await sushiContract?.approve(barContract?.address, ethers.constants.MaxUint256.toString())
```

2021-03-23 09:59 UTC, schystz commented on src/components/PositionCard/BalancerPoolCard.tsx
> +      setLoading({ ...loading, staking: false })
@ernestpascual after a failing transaction (out of gas error), the confetti still appears on the UI. Not sure why as the code looks fine here.

2021-03-23 11:02 UTC, schystz commented on src/components/PositionCard/BalancerPoolCard.tsx
> +        const approvalTxn = await lpTokenContract!.approve(HALO_REWARDS_ADDRESS, lpTokenAmount.toString())
Nvm, I tried it but it didn't helped. The allowance reset back to 0 after some time :(

2021-03-23 13:48 UTC, ernestpascual commented on src/components/PositionCard/BalancerPoolCard.tsx
> +        const approvalTxn = await lpTokenContract!.approve(HALO_REWARDS_ADDRESS, lpTokenAmount.toString())
infinite approval is actually discouraged but it's gives better ux tho. bad actors can exploit all your tokens that way. 

this a security vs UX decision. Since the bug doesn't seem to be connected with the way we're doing it now, i'd go for this than having vulnerabilities long term.

What do you think @ctverceles @tracyarciaga ? I don't mind doing the infinite approvals if we get a common decision

2021-03-23 13:49 UTC, ernestpascual commented on src/components/PositionCard/BalancerPoolCard.tsx
> +      setLoading({ ...loading, staking: false })
thanks for spotting! let me check on this

2021-03-23 14:06 UTC, ernestpascual commented on src/components/PositionCard/BalancerPoolCard.tsx
> +        const approvalTxn = await lpTokenContract!.approve(HALO_REWARDS_ADDRESS, lpTokenAmount.toString())
also useSaave hook seems to be something that combines aave deposit and sushibar deposit. Reference: https://etherscan.io/address/0x364762C00b32c4b448f39efaA9CeFC67a25603ff#code

(P.S. also this looks like a good defi lego piece. Earning in Aave and sushi at the same time.

2021-03-23 14:12 UTC, ernestpascual commented on src/components/PositionCard/BalancerPoolCard.tsx
> +  }, [bptBalance, getAllowance, getUnclaimedPoolReward, getUserTotalTokenslByPoolAddress, getBptBalance])
Fixing this!

2021-03-23 14:27 UTC, ernestpascual commented on src/components/PositionCard/BalancerPoolCard.tsx
> +      setLoading({ ...loading, staking: false })
so when its out of gas, it doesn't go to the catch block since a txn receipt is successfully returned. checking the status (1 if successful, 0 if failed) first before displaying the confetti. FYI @schystz thanks for spotting!

2021-03-23 15:58 UTC, ernestpascual commented on src/components/PositionCard/BalancerPoolCard.tsx
> +        const approvalTxn = await lpTokenContract!.approve(HALO_REWARDS_ADDRESS, lpTokenAmount.toString())
after doing `await lpTokenContract!.approve(HALO_REWARDS_ADDRESS, ethers.constants.MaxUint256.toString()`, approval doesnt appear anymore seems to fix the problem. if we are good with this i can go push this on next commit.

2021-03-24 05:46 UTC, schystz commented on src/components/PositionCard/BalancerPoolCard.tsx
> +        const approvalTxn = await lpTokenContract!.approve(HALO_REWARDS_ADDRESS, lpTokenAmount.toString())
Good catch, this fix looks good to me! :)

Good point on the security best practice. Though there is also the concern for gas fees (if allowing multiple times because of amount discrepancies) I would lean towards limiting the allowance to the transfer amount only, which is what we have currently.

2021-03-24 07:06 UTC, schystz commented on src/components/PositionCard/BalancerPoolCard.tsx
> +        const approvalTxn = await lpTokenContract!.approve(HALO_REWARDS_ADDRESS, lpTokenAmount.toString())
> after doing await lpTokenContract!.approve(HALO_REWARDS_ADDRESS, ethers.constants.MaxUint256.toString(), approval doesnt appear anymore seems to fix the problem. if we are good with this i can go push this on next commit.

Tried this too actually but after some time, the allowance reverts back to 0.

Could it be the problem is that `getAllowance()` on line 98 needs to be waited first? It sets `allowance` state to the value returned by `allowance()` contract call, but we are not sure that it will be reflected immediately on line 99 and/or succeeding lines (as this might rerender the component). I think it's better if we wait and return the allowance on `getAllowance()` instead of storing it on a state variable.

2021-03-24 07:24 UTC, ctverceles commented
@ernestpascual @schystz @tracyarciaga 

so i tried staking BPT tokens
1st 2 txs failed due to the gas estimation https://kovan.etherscan.io/tx/0xf86dc1c91d1e2e2295feb2c3c789b2df48a8231ebf9f98a72d693385941c7c34 , https://kovan.etherscan.io/tx/0x26c94f7ecb8c2b8d1d98ca0b563067f4e106629de79a72475981222bfd8445c1
3rd stake tx worked https://kovan.etherscan.io/tx/0xf86dc1c91d1e2e2295feb2c3c789b2df48a8231ebf9f98a72d693385941c7c34

Successful staking txs resulted in the confetti (yay!). Maybe we should make a custom Halo Halo animation for this later on.

The approve popup showed up for me twice, first for the 1st tx for 10 BPT which is expected, then again for the 2nd tx for 1 BPT which I guess is not expected.

2021-03-24 07:26 UTC, ctverceles requested changes
Essentially @schystz 's [comment](https://github.com/HaloDAO/halodao-interface/pull/2#discussion_r600220158). everything works for me (see prior [comment](https://github.com/HaloDAO/halodao-interface/pull/2#issuecomment-805568637))

2021-03-24 12:57 UTC, schystz commented
This looks good to me already. We can discuss & fix the allowance & rewards issue in the separate tasks we created yesterday. I suggest merging this once we have another set of eyes look closer at the changes, so we can proceed with reviewing the other PRs as well @ctverceles  @tracyarciaga

2021-03-24 12:58 UTC, schystz approved these changes

2021-03-25 01:57 UTC, ernestpascual commented on src/components/PositionCard/BalancerPoolCard.tsx
> +        const approvalTxn = await lpTokenContract!.approve(HALO_REWARDS_ADDRESS, lpTokenAmount.toString())
so @schystz you mean we call .allowance() everytime? I can check if this works and if not I can merge this instead.

2021-03-25 02:56 UTC, schystz commented on src/components/PositionCard/BalancerPoolCard.tsx
> +        const approvalTxn = await lpTokenContract!.approve(HALO_REWARDS_ADDRESS, lpTokenAmount.toString())
@ernestpascual yeah basically. Although `getAllowance()` is also called many times too actually (line 100 & 89), just not sure if the actual `allowance()` contract call is actually called since `getAllowance()` uses `useCallback()`)

I hope you don't mind as I already taken the liberty to push the suggested change here yesterday - https://github.com/HaloDAO/halodao-interface/pull/2/commits/49cde817f8ca1d2544168eb364ad1dfddb9c1bd1

Open for discussion though so let me know your thoughts.

2021-03-25 04:04 UTC, ctverceles approved these changes

2021-03-25 04:09 UTC, tracyarciaga approved these changes

2021-03-25 13:57 UTC, merged