Standard currency & balance formatting on pools page + added Swap & Vote menu to navbar
xave-finance/halodao-interface-archive pull request #21
Opened 2021-04-19 09:03 UTC by schystz

## Description of Changes

- HDF-142: Use balancer `formatNumber` function for formatting currencies and token balances throughout the app
- HDF-131: Create a "Swap" tab that when clicked redirects to the balancer swap page
- HDF-132: Create a "Vote" tab that when clicked redirects to our halodao snapshot page

## How to test

Check /pools page and verify that $ prices and HALO & BPT balances are showing up fine.

Swap and Vote tabs/menu added on navbar, and redirecting to correct url 

[Link to Jira Ticket](https://halodao.atlassian.net/browse/HDF-142, https://halodao.atlassian.net/browse/HDF-131, https://halodao.atlassian.net/browse/HDF-132)

### Developer Checklist:

- [x] This PR has a corresponding JIRA ticket
- [x] My branch conforms with our naming convention i.e. `feature/BGM-XXX-description`
- [ ] I have written new tests for your core changes, as applicable
- [x] I have successfully ran tests locally

### Reviewers Checklist:

- [ ] Code is readable and understandable; any unclear parts have explanations
- [ ] Code style confirms to typescript rules
- [ ] UI/UX changes match the corresponding figma/other design resources, if applicable
- [ ] I have successfully ran tests locally

2021-04-20 09:17 UTC, tracyarciaga reviewed
@schystz question for you  ->  screenshot below:
![image](https://user-images.githubusercontent.com/6169194/115371023-381a2480-a1fc-11eb-94c8-9e1ca89c067a.png)

2021-04-20 09:27 UTC, tracyarciaga requested changes

2021-04-20 09:27 UTC, tracyarciaga commented on src/components/Header/index.tsx
> +          </StyledExternalLink>
baliktad yung link @schystz :)

2021-04-20 09:47 UTC, schystz commented on src/components/Header/index.tsx
> +          </StyledExternalLink>
Thanks for the catch @tracyarciaga ! 🤦‍♂️

2021-04-20 09:50 UTC, schystz commented
> @schystz question for you -> screenshot below:
> ![image](https://user-images.githubusercontent.com/6169194/115371023-381a2480-a1fc-11eb-94c8-9e1ca89c067a.png)

For this one, we actually reused `formatNumber` function from balancer code and their rule here is to use 3 decimal digits as default for non-currency formatting:

```
  let format = '0.[000]'
  if (number > 1000) format = '0.[0]a'
  if (number < 1) format = '0.[0000]'
```

2021-04-20 13:09 UTC, schystz commented on src/components/Header/index.tsx
> +          </StyledExternalLink>
This is now resolved @tracyarciaga

2021-04-20 13:10 UTC, schystz commented
Thanks for the initial review @tracyarciaga! I believe all your feedback has now been addressed, please let me know should I missed anything or you still need clarification on something.

2021-04-21 08:10 UTC, barryhalo commented
@schystz Shouldn't we use the number formatter in pool summary also?

https://github.com/HaloDAO/halodao-interface/blob/4ab99c014518638e1b3834f7607d518501adb1ba/src/components/PoolsSummary/index.tsx#L80

https://github.com/HaloDAO/halodao-interface/blob/4ab99c014518638e1b3834f7607d518501adb1ba/src/components/PoolsSummary/index.tsx#L95

https://github.com/HaloDAO/halodao-interface/blob/4ab99c014518638e1b3834f7607d518501adb1ba/src/components/PoolsSummary/index.tsx#L100

https://github.com/HaloDAO/halodao-interface/blob/4ab99c014518638e1b3834f7607d518501adb1ba/src/components/PoolsSummary/index.tsx#L127

2021-04-21 08:14 UTC, schystz commented
> @schystz Shouldn't we use the number formatter in pool summary also?
> 
> https://github.com/HaloDAO/halodao-interface/blob/4ab99c014518638e1b3834f7607d518501adb1ba/src/components/PoolsSummary/index.tsx#L80
> 
> https://github.com/HaloDAO/halodao-interface/blob/4ab99c014518638e1b3834f7607d518501adb1ba/src/components/PoolsSummary/index.tsx#L95
> 
> https://github.com/HaloDAO/halodao-interface/blob/4ab99c014518638e1b3834f7607d518501adb1ba/src/components/PoolsSummary/index.tsx#L100
> 
> https://github.com/HaloDAO/halodao-interface/blob/4ab99c014518638e1b3834f7607d518501adb1ba/src/components/PoolsSummary/index.tsx#L127

Actually we do. Those values from the lines you mentioned are coming from `usePoolsSummary` hook, which already applies the formatting. See https://github.com/HaloDAO/halodao-interface/blob/4ab99c014518638e1b3834f7607d518501adb1ba/src/halo-hooks/usePoolsSummary.ts#L72

2021-04-21 08:16 UTC, barryhalo approved these changes
@schystz Looks good to me!

2021-04-22 01:39 UTC, tracyarciaga approved these changes

2021-04-22 07:16 UTC, merged