feature/hdf-102-vesting-page
xave-finance/halodao-interface-archive pull request #22
Opened 2021-04-20 02:28 UTC by barryhalo

## Description of Changes

- [UI/UX Redesign] Header section
- [UI/UX Redesign] Vesting card section
- [UI/UX Redesign] Extra info section

[Link to Jira Ticket  -  HDF 102](https://halodao.atlassian.net/browse/HDF-102)
[Link to Jira Ticket  -  HDF 103](https://halodao.atlassian.net/browse/HDF-103)
[Link to Jira Ticket  -  HDF 104](https://halodao.atlassian.net/browse/HDF-104)

2021-04-20 05:25 UTC, tracyarciaga requested changes
@barryhalo right  and  left padding (or margin) in mobile view -> too wide. Lessen the eight and left padding(or margin).
![image](https://user-images.githubusercontent.com/6169194/115341484-4c015e80-a1db-11eb-88f5-c795bb29b3a7.png)

2021-04-20 06:15 UTC, barryhalo commented
@tracyarciaga it's because laptop browser has a minimum width when you resize it, and that minimum width is larger than the mobile view hence the spaces on the side

Laptop browser, resized to smallest size/width
<img width="508" alt="Screen Shot 2021-04-20 at 2 07 55 PM" src="https://user-images.githubusercontent.com/81855319/115346115-55da9000-a1e2-11eb-883e-be1ee79b5e28.png">

Mobile/responsive mode/vide
<img width="1046" alt="Screen Shot 2021-04-20 at 2 07 10 PM" src="https://user-images.githubusercontent.com/81855319/115346187-71de3180-a1e2-11eb-968c-5bf6ab431d87.png">
<img width="943" alt="Screen Shot 2021-04-20 at 2 06 33 PM" src="https://user-images.githubusercontent.com/81855319/115346200-760a4f00-a1e2-11eb-9b07-930342136f87.png">

2021-04-21 00:28 UTC, barryhalo commented
@tracyarciaga fixed the spacing, for review

2021-04-21 02:16 UTC, schystz commented
Hi @barryhalo , is it possible to rebase this branch to `develop` just so it's easier to review? I see 96 commits and it doesn't seem like all of them has something to do with HDF-102.

2021-04-21 04:35 UTC, barryhalo commented
@schystz Rebasing from develop will not remove the merged commits from other branches since the merge is done in this branch

2021-04-21 10:50 UTC, schystz commented
Hi @barryhalo , here are some UI feedback:

- Can we make the page width the same as Farm page? Currently it is a little narrower
- Rename all occurrences of:
    - HaloHalo to HALOHALO
    - Halo to HALO
- The space below “DESSERT FACT” & paragraph below it is too tall (pls refer to Figma design for proper spacing)
- Button texts should be “Deposit” & “Claim HALO”

Will look at the code next & add just inline comments if I notice anything.

2021-04-21 11:58 UTC, schystz reviewed
Hi @barryhalo , added some inline comments. Aside from these, can you also fix the ESLint warnings on the files that was modified in this PR? (not required to fix the warnings on files that you didn't modified)

2021-04-21 11:58 UTC, schystz commented on public/locales/en.json
> +  "closeTxt": "Close"
@barryhalo duplicate key, already defined on line 106

2021-04-21 11:58 UTC, schystz commented on src/pages/HaloHalo/HALOHALODepositPanelMobile.tsx
> +import React, { useState, useCallback } from 'react'
@barryhalo I am having doubts about this strategy of creating another component for mobile layout. First is because the HTML footprint is heavier because although the mobile is hidden on desktop (or vice versa) the html code is still there, only it is hidden by CSS. The second reason is writing integration test will become more tricky as this requires adding an `id` to textfields and buttons, and since we have two set of buttons and textfields instead of 1, cypress might have trouble of identifying which is which.

Normally, we just handle mobile responsiveness via css breakpoints while the html code stays mostly the same for web and mobile. I can perhaps help out with this if this is something out of your expertise though.

2021-04-22 01:32 UTC, barryhalo commented on src/pages/HaloHalo/HALOHALODepositPanelMobile.tsx
> +import React, { useState, useCallback } from 'react'
@schystz That would be very helpful, let's discuss later, thanks!

2021-04-22 02:06 UTC, barryhalo commented
> * Button texts should be “Deposit” & “Claim HALO”

@schystz This has been fixed along w/ duplicate records in localization file

2021-04-22 02:36 UTC, tracyarciaga reviewed
@barryhalo I agree with @schystz as  much as  possible ->  use same  elements or components for responsiveness.

2021-04-23 01:05 UTC, barryhalo commented
> @barryhalo I agree with @schystz as much as possible -> use same elements or components for responsiveness.

@tracyarciaga @schystz This has been fixed, ready for review again

2021-04-23 05:52 UTC, tracyarciaga commented on src/pages/HaloHalo/index.tsx
>                daily HALO vesting multiples.
@barryhalo this is just super minor:
1. If  there is no way to do this, then it's ok to ignore
![image](https://user-images.githubusercontent.com/6169194/115823666-4d2fc700-a439-11eb-9a36-1c691ed42e24.png)

2. Left and right  padding not the same.
![image](https://user-images.githubusercontent.com/6169194/115824561-afd59280-a43a-11eb-9361-dafe1cb1e146.png)

2021-04-23 06:48 UTC, schystz reviewed
Hi @barryhalo , the new changes looks good to me. Glad that we were able to take out the mobile components!

Just 1 last query - how difficult it is to change the button names to Deposit and Claim HALO? I am guessing there might be some kind of existing logic there that updates the button text which depends if user has already approved the amount before. If its pretty straightforward let's take care of it now so the button titles matches Jofo's design.

2021-04-23 07:12 UTC, barryhalo commented
@tracyarciaga Side padding is the same already, left was 27px and right was 40px before, made them both 27px
<img width="410" alt="Screen Shot 2021-04-23 at 3 08 12 PM" src="https://user-images.githubusercontent.com/81855319/115832675-bc131d00-a445-11eb-9f99-b86efcf56c2a.png">

This is what will happen if we want the APY in one line, either we drastically reduce the side padding or make the font size smaller, but it won't be the same w/ other section's font size
<img width="393" alt="Screen Shot 2021-04-23 at 3 10 34 PM" src="https://user-images.githubusercontent.com/81855319/115832939-114f2e80-a446-11eb-9ea0-c00a06553555.png">

2021-04-23 07:38 UTC, tracyarciaga commented
> @tracyarciaga Side padding is the same already, left was 27px and right was 40px before, made them both 27px
> <img alt="Screen Shot 2021-04-23 at 3 08 12 PM" width="410" src="https://user-images.githubusercontent.com/81855319/115832675-bc131d00-a445-11eb-9f99-b86efcf56c2a.png">
> 
> This is what will happen if we want the APY in one line, either we drastically reduce the side padding or make the font size smaller, but it won't be the same w/ other section's font size
> <img alt="Screen Shot 2021-04-23 at 3 10 34 PM" width="393" src="https://user-images.githubusercontent.com/81855319/115832939-114f2e80-a446-11eb-9ea0-c00a06553555.png">

Okay thanks Barry! I am good. I approve your changes.

2021-04-23 07:41 UTC, schystz approved these changes

2021-04-23 07:45 UTC, barryhalo commented
@tracyarciaga @schystz 

For improvement

Better if buttons default text are `Deposit` and `Claim HALO`, then after the user enter an amount, that's the time the button text will change to `Approve` if not yet approved or if user has no balance

2021-04-23 07:47 UTC, merged