new ABI, updated UI, new rewards contract support
xave-finance/halodao-interface-archive pull request #25
Opened 2021-04-27 19:45 UTC by ernestpascual

- new HaloHalo abi
- made APY value and price dynamic
- modified useHaloHalo to support new HaloHalo contract version

2021-04-28 02:51 UTC, bitcoinbrisbane commented on src/constants/index.ts
>  // HALO Chest Addressess
```suggestion
// HALOHALO Addressess
```

2021-04-28 02:53 UTC, bitcoinbrisbane commented on src/halo-hooks/useHaloHalo.ts
> +          //const tx = await halohaloContract?.leave(ethers.utils.parseUnits(amount)) // where amount is string
Can we remove?

2021-04-28 02:54 UTC, bitcoinbrisbane requested changes
Few things to change, plus the linting issues.

2021-04-28 04:20 UTC, ernestpascual commented on src/halo-hooks/useHaloHalo.ts
> +          //const tx = await halohaloContract?.leave(ethers.utils.parseUnits(amount)) // where amount is string
thanks for spotting! will remove

2021-04-28 05:20 UTC, ernestpascual commented
Updated: 
- number formatting
- better managment of APY calculation

2021-04-28 06:42 UTC, schystz commented
Checked the code and tested this locally too - worked and looks good to me! :) Nice job @ernestpascual !

I have some feedback on how to improve UX but I'll add it in this Jira task instead https://halodao.atlassian.net/browse/HDF-164 since it has nothing to do with the changes in this PR.

Also, I'll leave the verification of APY & HALOHALO:HALO ratio calculation to @ctverceles

2021-04-28 06:45 UTC, schystz commented
Actually, I just noticed that integration tests is failing for this PR. Can you take care of it too @ernestpascual ? Please refer to `INTEGRATION_TESTS.md` for howto, but you can also ping me for immediate help.

2021-04-28 06:54 UTC, ernestpascual commented
Updated cypress test. All things are passing on my end @schystz

2021-04-28 07:04 UTC, schystz reviewed
@ernestpascual a couple of suggestions for integration testing of Vesting page

2021-04-28 07:04 UTC, schystz commented on cypress/integration/vesting.test.ts
>      // cy.should('not.contain', '% APY')
@ernestpascual what I envision for this test actually is that "% APY" is displayed initially until APY is calculated, in that case "% APY" is replaced with "0.31% APY"

2021-04-28 07:04 UTC, schystz commented on cypress/integration/vesting.test.ts
>      // cy.should('not.contain', '% APY')
Can we also add a similar test for line #14 below? So, initially check that ratio is undefined or 0, then should update to non-undefined/zero

2021-04-28 08:19 UTC, ernestpascual commented
added additional tests and everything is passing. @schystz

2021-04-28 08:20 UTC, schystz approved these changes
Thanks @ernestpascual !

2021-04-29 01:29 UTC, tracyarciaga requested changes
Approving this with just minor request.

2021-04-29 01:29 UTC, tracyarciaga commented on src/constants/index.ts
> +  [ChainId.KOVAN]: process.env.REACT_APP_HALOHALO_ADDRESS_KOVAN || ''
@ernestpascual Super minor request, can u also add the REACT_APP_HALOHALO_ADDRESS_KOVAN in the env.example file.

2021-04-29 02:59 UTC, ernestpascual commented
done @tracyarciaga !

2021-04-30 02:25 UTC, ctverceles approved these changes
So (using the `halodao-interface.env` file here https://halodao.1password.com/vaults/gllrg2so74fsgd43baj5q5voui/allitems/nb3dl4j5frbhlleg2vn4wuw6ay) I ran the UI locally while pointed to kovan and checked the total HALOHALO supply here https://kovan.etherscan.io/token/0x4507557aFd5109Fd09cD18B8BFFa625b2c37C7b5#balances. Based on that, HALOHALO:HALO price = 723/(166.67 + 46.43 + 10.38 + 0.3) = 3.2308517... which roughly equals the calculation on the preview link 
![image](https://user-images.githubusercontent.com/16344192/116640801-f2005600-a99d-11eb-9d6e-7e438ce43f3f.png)

The APY i guess is a bit harder to double check atm. i'll need to run the contracts and UI locally for a day to confirm, but the code does make sense and the APY value on the Vesting page seems to make sense when i do the math. @bitcoinbrisbane @tracyarciaga given this, do we ;

- leave it under Peer Review and not yet merge 
- or move to Testing and merge this?

2021-04-30 03:22 UTC, schystz commented
@ctverceles @tracyarciaga I vote to merge this PR, so we can proceed with re-initing the repo, and me submitting my PR for HDF-152 which can be done today.

2021-04-30 03:32 UTC, tracyarciaga commented
> * leave it under Peer Review and not yet merge

@ctverceles @ernestpascual I just read @schystz comment.  With that, let's just merge it and move to it testing. So James can fast-track his PR too.

2021-04-30 03:36 UTC, merged