Feature/bgm 673 update documentations on code repo
xave-finance/halodao-interface-archive pull request #5
Opened 2021-03-25 08:09 UTC by tracyarciaga

## Description of Changes

Add documentation for diagrams and template for troubleshooting guide.
 
[Link to Jira Ticket](https://halodao.atlassian.net/browse/HDF-36?atlOrigin=eyJpIjoiMTk1NTM4NGZiMzE4NGE1OGIwZWQzZTQyODUzN2Q3MjUiLCJwIjoiaiJ9)

### Developer Checklist:

* [ ] I have followed the guidelines in our Contributing document
* [ ] This PR has a corresponding JIRA ticket
* [ ] My branch conforms with our naming convention i.e. `feature/BGM-XXX-description`
* [ ] All files have appropriate file headers and documentation
* [ ] I have written new tests for your core changes, as applicable
* [ ] I have successfully ran tests locally

### Reviewers Checklist:
* [ ] Code is readable and understandable; any unclear parts have explanations 
* [ ] Code style confirms to eslint/flow rules
* [ ] UI/UX changes match the corresponding figma/other design resources, if applicable
* [ ] I have successfully ran tests locally

2021-03-25 14:07 UTC, ernestpascual reviewed
Same q from https://github.com/HaloDAO/emp-tools/pull/6#pullrequestreview-621153049!

2021-03-26 03:54 UTC, schystz commented on .github/pull_request_template.md
> +[Link to Jira Ticket](https://soowhq.atlassian.net/browse/SOOW-)
@tracyarciaga can we replace the link with `https://halodao.atlassian.net/browse/HDF-` so its easier to simply append the issue number at the end?

2021-03-27 02:00 UTC, ctverceles commented on .github/pull_request_template.md
> +[Link to Jira Ticket](https://soowhq.atlassian.net/browse/SOOW-)
+1

2021-03-27 02:05 UTC, ctverceles requested changes
Very minor notes just to update some things and clarify others! Thanks for getting the docs started @tracyarciaga !

2021-03-27 02:05 UTC, ctverceles commented on .github/pull_request_template.md
> +[Link to Jira Ticket](https://soowhq.atlassian.net/browse/SOOW-)
+1

2021-03-27 02:05 UTC, ctverceles commented on .github/pull_request_template.md
> +* [ ] Code style confirms to eslint/flow rules
Are we using eslint/flow now? Or maybe this is just leftover from the template. Can remove @tracyarciaga ?

2021-03-27 02:05 UTC, ctverceles commented on CONTRIBUTING.md
> +- Nodejs `v8.16.2`. We **strongly** recommend you install via [NVM](https://github.com/creationix/nvm) to avoid incompatibility issues between different node projects.
shall we change this to 14.15 @tracyarciaga @schystz @ernestpascual ? what are we all using for this repo?

2021-03-27 02:05 UTC, ctverceles commented on CONTRIBUTING.md
> +   nvm install v8.16.2
same node version comment here

2021-03-27 02:05 UTC, ctverceles commented on CONTRIBUTING.md
> +   nvm use v8.16.2
same node version comment here

2021-03-27 02:05 UTC, ctverceles commented on CONTRIBUTING.md
> +- Check that the correct node (8.16.2) and npm (6.4.1) versions are installed
same node version comment here

2021-03-27 02:05 UTC, ctverceles commented on CONTRIBUTING.md
> +- [Solidity](https://docs.soliditylang.org/en/v0.8.2/style-guide.html)
latest version here! https://docs.soliditylang.org/en/v0.8.3/style-guide.html

2021-03-27 02:05 UTC, ctverceles commented on docs/diagrams.md
> + * [Deposit xHALO, withdraw HALO](https://halodao.atlassian.net/wiki/spaces/HALODAO/pages/721251/Diagrams#Halo-Chest%3A-Deposit-xHALO%2C-withdraw-HALO)
great diagrams @tracyarciaga ! thanks for this initiative to make things clearer for everyone :)

2021-03-27 02:08 UTC, ctverceles commented on .github/pull_request_template.md
> +* [ ] My branch conforms with our naming convention i.e. `feature/BGM-XXX-description`
`feature/HDF-XXX-description`

2021-03-27 17:35 UTC, ernestpascual commented on CONTRIBUTING.md
> +You may follow base configurations for Prettier here https://github.com/prettier/prettier-vscode.
@schystz  do we make our prettier config as the standard?

2021-03-29 23:19 UTC, tracyarciaga commented on CONTRIBUTING.md
> +You may follow base configurations for Prettier here https://github.com/prettier/prettier-vscode.
@ernestpascual I think we should

2021-03-29 23:21 UTC, merged